FROM apache/airflow:2.7.1-python3.9

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir dbt-snowflake boto3 requests faker pandas numpy awscli
